### ISSUE TITLE
Auto disable IPv6

### ISSUE THREAD

**Issue by S0h1n1** [bissisoft/torall#7]
Hey guys 😃 It would be nice if you can add auto-disable for IPv6 on START and then re-enable it back on STOP.
At the moment I manually disable ipv6 but sometimes it's easy to forget 😉
I know I can disable it globally on boot but, I need to use IPv6 for some other things.
Thank you kindly.

Very trully yours,
Sohini.

**Comment by bissito** [comment]
> Hey guys smiley It would be nice if you can add auto-disable for IPv6 on START and then re-enable it back on STOP. At the moment I manually disable ipv6 but sometimes it's easy to forget wink I know I can disable it globally on boot but, I need to use IPv6 for some other things. Thank you kindly.
> 
> Very trully yours, Sohini.

**Comment by bissito** [comment]
@S0h1n1 Should be no problem :+1: and you also gave me idea for another feature and more enhancements :grin:
