### ISSUE TITLE
Integrate MAC address spoofing by default

### ISSUE THREAD

**Issue by bissito** [bissisoft/torall#9]
- [x]  build.sh --> Install macchanger (if not installed)

- [x]  torall.py - On --start --> Set fully random MAC addresses on all interfaces

- [x]  torall.py - On --stop --> Reset all interfaces to the original, permanent hardware MAC addresses

**Comment by TheKidEmil** [comment]
@bissito Please check out on the testing branch. I implemented 2 new functions -- `spoof_mac_addresses()` and `revert_mac_addresses()` but  I have comment out the calls to them for they seem to bug up, mess up, and slow down the other processes :disappointed: Look for IPv6 and NetworkManager problems mostly. Also, check iptables and firewall as well. Thank you.

**Comment by bissito** [comment]
@TheKidEmil Fixed :+1:
